name: Docker Build and Send Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_NUMBER: "${{ github.event.number }}"

jobs:
  Build-Image-And-Send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        - name: Build the Docker image
        run: |
        if [ -z ${PR_NUMBER} ]; then
        docker run --name mynginximage -p 80:80 -d image-nginx:latest
        else
        docker run --name mynginximage -p 80:80 -d image-nginx:${PR_NUMBER}
        fi 

      - name: Run the Docker image
        run: docker run --name mynginximage -p 80:80 -d image-nginx:${PR_NUMBER}

      - name: Show images
        run: docker image ls | grep image-nginx

      - name: test url
        run: |
          curl -X GET "http://localhost"