name: Docker Build and Send Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_NUMBER: "${{ github.event.number }}"

jobs:
  Build-Image-And-Send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          if test -n "${PR_NUMBER}"; then
          docker build . --file Dockerfile --tag image-nginx:PR-${PR_NUMBER}
          else
          docker build . --file Dockerfile --tag image-nginx:latest
          fi

      - name: Run the Docker image
        run: |
          if test -n "${PR_NUMBER}"; then
          docker run --name mynginximage -p 80:80 -d image-nginx:PR-${PR_NUMBER}
          else
          docker run --name mynginximage -p 80:80 -d image-nginx:latest

      - name: Show images
        run: docker image ls

      - name: test url
        run: |
          curl -X GET "http://localhost"