name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update System
      run: sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install openssl policycoreutils -y

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag image-nginx:latest

    - name: Run the Docker image
      run: docker run --name mynginximage -p 80:80 -d image-nginx:latest

    - name: test url
      run: |
        curl -X GET "http://localhost"

  Ubuntu:

    runs-on: ubuntu-latest
    needs: [ Build ]

    steps:
    - uses: actions/checkout@v3
    - name: Show enviroment run in github action
      run: cat /etc/issue
