name: Docker Build and Send Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-Image-And-Send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Show envs
        run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag image-nginx:latest

      - name: Run the Docker image
        run: docker run --name mynginximage -p 80:80 -d image-nginx

      - name: test url
        run: |
          curl -X GET "http://localhost"