name: Docker Build and Send Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_Image_And-Send:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag image-nginx:latest

      - name: Run the Docker image
        env:
          PR_NUMBER: $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        run: |
        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        docker run --name mynginximage -p 80:80 -d image-nginx:${PR_NUMBER}

      - name: test url
        run: |
          curl -X GET "http://localhost"