name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set envs
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export DEBCONF_NONINTERACTIVE_SEEN=true

    - name: save debconf
      run: |
        sudo printf 'tzdata tzdata/Areas select Etc\ntzdata tzdata/Zones/Etc select UTC\n' | debconf-set-selections

    - name: Install dependencies
      run: |
        sudo apt-get install openssl policycoreutils libxml2 -y
        which openssl
        dpkg -l | grep  policycoreutils

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag image-nginx:latest

    - name: Run the Docker image
      run: docker run --name mynginximage -p 80:80 -d image-nginx:latest

    - name: test url
      run: |
        curl -X GET "http://localhost"

  Ubuntu:

    runs-on: ubuntu-latest
    needs: [ Build ]

    steps:
    - uses: actions/checkout@v3
    - name: Show enviroment run in github action
      run: cat /etc/issue
