#test 3
name: Test envs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_NUMBER: "${{ github.event.number }}"
  PATH_REPO_DOCKER: "hub.docker.hpecorp.net/pivs/"
  PATH_REPO_DOCKER2: "hub.docker.hpecorp.net/pivs/"

jobs:

  popular_variavel:
  runs-on: ubuntu-latest
  steps:
  - name: salvar saida
      id: variavel_test
      uses: actions/checkout@v2
      run: echo "Nova variavel"
  outputs:
    nova_variavel: ${{ steps.variavel_test.outputs.nova_variavel }}
    
  using_other_repo:
    needs: variavel_test
    uses: RoneySantos/lab-notifier-jenkins-ia/.github/workflows/test_to_use_other_repo.yaml@main


  # test_continuous:
  # runs-on: ubuntu-latest
  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Apenas um teste
  #     run: date

# jobs:
#   Build-Image-And-Send:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
      
#       - name: Teste usando repo atual
#         run: echo ${PATH_REPO_DOCKER}${{github.repository}}
