#test 33
name: Test envs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_NUMBER: "${{ github.event.number }}"
  PATH_REPO_DOCKER: "hub.docker.hpecorp.net/pivs/"
  PATH_REPO_DOCKER2: "hub.docker.hpecorp.net/pivs/"
  CURRENT_REPO: "${{ github.repository }}" 

jobs:

  popular_variavel:

    runs-on: ubuntu-latest
    steps:
      - name: Tratar variavel
        id: variavel_test
        run: |
        CURRENT_REPO2=$(echo $CURRENT_REPO | awk -F '/' '{print $2}') >> $GITHUB_ENV

      - name: usando o valor
        run: echo "${{ env.CURRENT_REPO2 }}"
    # outputs:
      # nova_variavel: ${{ steps.variavel_test.outputs.nova_variavel }}

  # testando_variavel:
    # runs-on: [self-hosted, "${{ steps.variavel_test.outputs.nova_variavel }}"]
    # needs: variavel_test
    # steps:
      # - name: Mostrar variavel
        # run: echo ${{ steps.variavel_test.outputs.nova_variavel }}
    
  # using_other_repo:
    # needs: variavel_test
    # uses: RoneySantos/lab-notifier-jenkins-ia/.github/workflows/test_to_use_other_repo.yaml@main


  # test_continuous:
  # runs-on: ubuntu-latest
  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Apenas um teste
  #     run: date

# jobs:
#   Build-Image-And-Send:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
      
#       - name: Teste usando repo atual
#         run: echo ${PATH_REPO_DOCKER}${{github.repository}}
