#test 333
name: Test envs

on:
  workflow_call:
    inputs:
      image_repo:
        description: Testando envio de variaveis
        default: "echo 'IMAGE_REPO=hss-apigw' >> $GITHUB_ENV"
        required: false
        type: string

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_NUMBER: "${{ github.event.number }}"
  PATH_REPO_DOCKER: "hub.docker.hpecorp.net/pivs/"
  PATH_REPO_DOCKER2: "hub.docker.hpecorp.net/pivs/"
  CURRENT_REPO: "${{ github.repository }}" 
  TESTANDO: TESTANDOISSO

jobs:

  mostrar_variavel:
    
  popular_variavel:
    uses: RoneySantos/lab-notifier-jenkins-ia/.github/workflows/test_to_use_other_repo.yaml@main


