name: Docker Build and Send Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_NUMBER: "${{ github.event.number }}"
  PATH_REPO_DOCKER: "hub.docker.hpecorp.net/pivs/"

jobs:
  using_other_repo:
    uses: RoneySantos/lab-notifier-jenkins-ia/.github/workflows/test_to_use_other_repo.yaml

  # test_continuous:
  # runs-on: ubuntu-latest
  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Apenas um teste
  #     run: date

# jobs:
#   Build-Image-And-Send:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
      
#       - name: Teste usando repo atual
#         run: echo ${PATH_REPO_DOCKER}${{github.repository}}