#test 333
name: Test envs

on:
  workflow_call:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_NUMBER: "${{ github.event.number }}"
  PATH_REPO_DOCKER: "hub.docker.hpecorp.net/pivs/"
  PATH_REPO_DOCKER2: "hub.docker.hpecorp.net/pivs/"
  CURRENT_REPO: "${{ github.repository }}" 
  TESTANDO: TESTANDOISSO

jobs:

  popular_variavel:
    uses: RoneySantos/lab-notifier-jenkins-ia/.github/workflows/test_to_use_other_repo.yaml@main
    with:
      image_repo: "repos='api-gateway/cmd/apigw/\nauthentication/cmd/accounts/'"



